services:
  - type: static
    name: portfolio-frontend
    rootDir: .
    buildCommand: npm ci && npm run build
    publishPath: dist
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
    envVars:
      - key: VITE_API_BASE
        # Set this to the backend URL after deploying backend, e.g. https://portfolio-backend.onrender.com
        value: "https://portfolio-backend.onrender.com"

  - type: web
    name: portfolio-backend
    rootDir: backend
    env: node
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
      - key: FRONTEND_ORIGIN
        # Set this to your frontend static site URL after first deploy.
        value: "https://dheerajgaurofficial.netlify.app"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: TO_EMAIL
        sync: false
